# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
